### ISSUE TITLE
Server Status should check liveness more than on page load

### ISSUE THREAD

**Issue by tarrekshaban** [IntrinsicLabsAI/intrinsic-model-server#37]
<img width="481" alt="image" src="https://github.com/IntrinsicLabsAI/intrinsic-model-server/assets/8039711/1e768c26-5fe9-4d6d-a548-02044f4d3b32">
Right now the server status component only checks status on first load of the page, we should implement a liveness check that refreshes more regularly to give the right impression to users.

**Comment by a10y** [comment]
I can add a new liveness endpoint, something that's going to be considerably cheaper to poll than the getAllModels endpoint.

interface:

```
/v1/ping

"pong"
```
